# Generated by Django 5.0.6 on 2024-06-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='asignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
