version: '3.10'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend
    command: npm start
    develop:
      watch:
        - path: ./frontend/src
          action: sync
          target: /app/src

  backend:
    build:
      context: ./backend
    command: >
      sh -c "python manage.py migrate && gunicorn server.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - '8000:8000'
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    develop:
      watch:
        - path: ./backend/server
          action: sync
          target: /app/server
        - path: ./backend/account
          action: sync
          target: /app/account

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
